# Site
repository: deepakgahlot98/aboutme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Deepak Gahlot
title: Developer - Android
email: deepakgahlot98@gmail.com
website: https://github.com/deepakgahlot98

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  deepakgahlot98
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: https://www.instagram.com/codkiller0911/
linkedin_username: https://www.linkedin.com/in/deepak-gahlot-4b7832102/
medium_username: https://medium.com/@codkiller0911
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Deepak and I'm a currently working at SAP as a Android Developer with an Experience of 6 years into Android Developement.

  I am most skilled in: <mark>Android</mark> and <mark>Web Developement</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/deepakgahlot98
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SAP
        link: sap.com
        # link_text: boringcompany.com
        sub_title: Developer
        caption: October 2020 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Working on the product called Ariba by SAP. SAP Ariba is the only procurement and supply chain collaboration solution that empowers compaines to move faster and spend better. With SAP Ariba, compaines can connect to the largest B2B network, creating dynamic, digital collaboration with millions of suppliers and other trading partners all around the world.
          I work on the Supplier side Android App for Ariba.

      - layout: left
        title: Adobe Inc
        link: adobe.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: June 2014 - September 2020
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Wokred on the one the Adobe most used product for photo editing "Lightroom". I was the part of the Android team and we were mainly working on developing the features for the Lightroom app on Android. Some of the features on which i worked intensively are Selective Edits, Copy-paste settings, Profiles & Presets.,

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Uttarakahand Technnical University
        caption: 2008 - 2012
        sub_title: B.Tech in Eletronics and Communication

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Cooking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
